### ISSUE TITLE
Is it possible to use a pretrained model from another type of tasks?

### ISSUE THREAD

**Issue by charlesxu90** [devalab/molgpt#6]
Dear author,

I saw multiple types of tasks in your study, e.g. without properties or scaffolds, with only one properties, and with scaffolds. 

It is possible to use a model pretrained from one type of task on another using your code? Or that's theoretical not plausible?

**Comment by VirajBagal** [comment]
Yeah it is possible to use from one property to other property. But weights trained on scaffold-condition cant be used for property-conditioned generation.

**Comment by charlesxu90** [comment]
Get it. Thanks.
